import '@fortawesome/fontawesome-free/js/fontawesome'
import '@fortawesome/fontawesome-free/js/solid'
import '@fortawesome/fontawesome-free/js/regular'
import '@fortawesome/fontawesome-free/js/brands'
import 'pure';
import 'base';
import 'grids';
import 'grids-responsive';
import 'jquery.cookie';
import 'chart';
import 'jscolor';
import './admin/admin.css';
import './assets/js/upload.js'
import './assets/js/charts-pks.js';
import './assets/js/functions.js';
import './admin/admin-events.js';
import './admin/admin-functions.js';
import './admin/admin.js';