import "jquery.cookie";
import 'jscolor';
import './admin/admin.css';
import './assets/js/upload.js'
import './assets/js/charts-pks.js';
import './assets/js/functions.js';
import './admin/admin-events.js';
import './admin/admin-functions.js';
import './admin/admin.js';