import "jquery.cookie";
import "jquery-ui-slider";
import './assets/css/playlist.css';
import './assets/js/functions.js';
import './assets/js/playlist-control.js';
import './assets/js/access_log.js';
import './assets/js/playlist.js';
import './assets/js/visualizer.js';
import './assets/js/charts-pks.js'
import './assets/js/index.js';
