import '@fortawesome/fontawesome-free/js/fontawesome'
import '@fortawesome/fontawesome-free/js/solid'
import '@fortawesome/fontawesome-free/js/regular'
import '@fortawesome/fontawesome-free/js/brands'
import 'pure';
import 'base';
import 'grids';
import 'grids-responsive';
import 'chart';
import './assets/css/playlist.css';
import "jquery-ui-slider";
import "jquery.cookie";
import './assets/js/functions.js';
import './assets/js/playlist-control.js';
import './assets/js/access_log.js';
import './assets/js/playlist.js';
import './assets/js/visualizer.js';
import './assets/js/charts-pks.js'
import './assets/js/index.js';
